services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - task-network
  database:
    container_name: database 
    image: postgres:14.0-alpine
    volumes:
      - v-database:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - task-network

volumes:
  v-database:

networks:
  task-network:
    driver: bridge
 
