name: Build dev

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker compose build
        run: make build-dev 
        env:
          POSTGRES_PORT: {{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: {{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: {{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: {{ secrets.POSTGRES_DB }}
          POSTGRES_HOST: {{ secrets.POSTGRES_HOST }}
          TASKS_POSTGRES_DSN: {{ secrets.TASKS_POSTGRES_DSN }}
